{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "notifier",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "notifier-0.8.0.jar",
          "url": "notifier-0.8.0.jar",
          "size": 34191,
          "sha512": "d44a820c7c1202521aa0eeecbe063f742773352d75e8cc1017c20e4a600282c36c8a36e25762a4d11a3dcdd6acb77f6ebb8cbdbcf04ea5cabd067e4317999397",
          "sha256": "cd54a72258a68740c0d83e8a01015d7608f69146e3dc335a811ed9f73d4d4d0e",
          "sha1": "5216e1dca64f859b6a8fb31b652057fbe4082d96",
          "md5": "c2facefe56690b3fbaf9a44ca722b7b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "notifier-0.8.0.jar",
          "url": "notifier-0.8.0.jar",
          "size": 34191,
          "sha512": "d44a820c7c1202521aa0eeecbe063f742773352d75e8cc1017c20e4a600282c36c8a36e25762a4d11a3dcdd6acb77f6ebb8cbdbcf04ea5cabd067e4317999397",
          "sha256": "cd54a72258a68740c0d83e8a01015d7608f69146e3dc335a811ed9f73d4d4d0e",
          "sha1": "5216e1dca64f859b6a8fb31b652057fbe4082d96",
          "md5": "c2facefe56690b3fbaf9a44ca722b7b3"
        }
      ]
    }
  ]
}
