{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "notifier",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "notifier-0.9.0.jar",
          "url": "notifier-0.9.0.jar",
          "size": 43512,
          "sha512": "686543a5a29a7727bc9571c34b98613a4787232bf0a9e48e0c3afac4a89d7f8d1290be9f888cb66ee6fe6e020e7e2bc09f5dde4ce8be9c6d65e184a26f4acd3b",
          "sha256": "845a0081df91bcdd3ec9fe06e7cf5b3204ec19a89988830ff7baccac192122c0",
          "sha1": "9b2c243ab5bf303ec44b5ecc93f15caf52429f6b",
          "md5": "13534afe7ab7907cb19e62bde07626d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "notifier-0.9.0.jar",
          "url": "notifier-0.9.0.jar",
          "size": 43512,
          "sha512": "686543a5a29a7727bc9571c34b98613a4787232bf0a9e48e0c3afac4a89d7f8d1290be9f888cb66ee6fe6e020e7e2bc09f5dde4ce8be9c6d65e184a26f4acd3b",
          "sha256": "845a0081df91bcdd3ec9fe06e7cf5b3204ec19a89988830ff7baccac192122c0",
          "sha1": "9b2c243ab5bf303ec44b5ecc93f15caf52429f6b",
          "md5": "13534afe7ab7907cb19e62bde07626d1"
        }
      ]
    }
  ]
}
